### ISSUE TITLE
Initial database connection

### ISSUE THREAD

**Issue by brandondombrowsky** [SeattleColleges/belindas-closet-android#1]
## User Story

As a Project manager doing some development, I will need to connect my team's base mobile app to a database. I will work with my lead engineer on a plan and workflow to make this successful.

Story Points: 6-12

### .env setup
- We will use .env to manage environment variables
- https://www.dotenv.org/docs/languages/kotlin.html

**Comment by brinkbrink** [comment]
Had meeting with LE, just waiting to see if we will use MongoDB or AWS for initial DB.
