### ISSUE TITLE
USER STORY: Admin View Page

### ISSUE THREAD

**Issue by taylorpapke** [SeattleColleges/belindas-closet-android#109]
As an admin, I will want to have a page that allows me to edit users, create and view products so that I can manage users and my inventory on the app.

![Image](https://github.com/SeattleColleges/belindas-closet-android/assets/94101953/a8ffa5f3-ecc0-428e-bb9e-b9f017d356e3)

Sign in and have Admin options available:
- Create an Edit User Role, routing admin to a separate page (Edit User View) allowing them to give user(s) certain permissions
- Add product page link: Create an add product button that routes to the add product page allowing them to add products
- Create a View All Products button, routing them to the landing page where creator’s can view all products
- Sign out button and functionality on nav bar

**Comment by Annelisebx** [comment]
@brandondombrowsky @taylorpapke 
I want to confirm a few pieces of this User Story:
1. This Admin View Page will only be accessible if the user is successfully signed in with an 'admin' login account? 
2. Is this is the only screen they will see and have access to? 
3. Do we currently have login guardrails in place for authenticating users? 
![image](https://github.com/SeattleColleges/belindas-closet-android/assets/50610153/cc156c23-a2de-4fa1-99bd-0019f2d5d5c9)

**Comment by taylorpapke** [comment]
Hi @Annelisebx,
i. Yes, the admin view will only be accessible if the user is successfully signed in with an 'admin' login account.
ii. Yes, this is the page that they will redirect to after they successfully sign in. After Tin's PR https://github.com/SeattleColleges/belindas-closet-android/pull/140 gets approved and merged in, you will be able to see that it currently is redirecting to the add product page. We should change this so that it routes to the admin page which includes the add product page button link.
iii. Similar to above. Once Tin's PR is merged in, we will be able to sign up users with admin access only using the front end UI and log them in so this is a great time to implement this page. I would start by walking through the PR above so you know how it functions. It does require you to have the backend set up with your personal mongoDB database.
