### ISSUE TITLE
USER STORY: GitHub documentation

### ISSUE THREAD

**Issue by brandondombrowsky** [SeattleColleges/belindas-closet-android#142]
As a developer and/or technical writer, I will want to make sure the team’s work is well documented. This will include further developing and creating consistency between the two client repos and their respective ReadMes and Wikis. 

I will want to work on and bring consistency to the following documents:
- [x] belindas-closet ReadMe
- [ ] belindas-closet Wiki
- [ ] belindas-closet-android ReadMe
- [ ] belindas-closet-android Wiki
- [ ] belidnas-closet-nestjs ReadMe
- [ ] belidnas-closet-nestjs Wiki

Also, within the "main" ReadMe (belindas-closet) I will want to add the progress videos that the Product Owners have been sharing with clients, as well as a brief summary, listing them under MVP1 and MVP2 as appropriate.

**Note** To ensure consistency, I will want to ideally work on this task with two screens open at the same time. One open to the ReadMe or Wiki I am working on, one open to the same document belonging to the other client ReadMe/Wiki. I will also want to confer with my documentation counterpart on the other project as we plan a workflow that ensures we are consistent.

**Comment by taylorpapke** [comment]
@brinkbrink I was being linked to Belindas-closet repo from nsc-events (android and nestjs) wiki and accidentally added what I was going to add to nsc-events wiki in regards to user story/issue naming: https://github.com/SeattleColleges/belindas-closet/wiki/User-Story-&-Issue-Naming-Conventions

Let me know what you think. I also added the missing wiki pages from Belindas-closet to nsc events wiki and rerouted all nsc-events (android and nestjs) wikis to nsc-events wiki.

**Comment by taylorpapke** [comment]
Marking as completed. I carried over and checked a lot of the documentation for the wikis and readmes when I was working on nsc-events.
