### ISSUE TITLE
Products in same category all go to the same place

### ISSUE THREAD

**Issue by nickolasram** [SeattleColleges/belindas-closet-android#150]
If products are in the same category, clicking on either takes the user to the same individual product page.
Cause: I believe it is because we're currently using the product's type to distinguish them
Solution: products need unique IDs

**Comment by tinpham5614** [comment]
_Comment:_ We have ObjectIds as unique IDs since we using MongoDB as below:
![image](https://github.com/SeattleColleges/belindas-closet-android/assets/72054441/3e038d31-de6a-45b5-b765-9a8588ee52f7)
