### ISSUE TITLE
Different layout for individual product page

### ISSUE THREAD

**Issue by nickolasram** [SeattleColleges/belindas-closet-android#158]
I just finished creating a different version for the individual product page and would like feedback to see if this is the direction we would like to go.
While the card-based layout is great for users to quickly scroll through a list of items, I figured the individual product page could be laid out differently. Since the page only displays one product and might have to display more information than the cards on the ProductDetail page, I tried breaking the individual product page out of the card-based layout. This way text elements can utilize more space than when they were crammed inside a card. Here's a screenshot:
![newpage (1)](https://github.com/SeattleColleges/belindas-closet-android/assets/91910852/c81f2f67-0ad2-4d52-8ecb-0fd5f706f391)

As you can see, I still kept a border around the image for visual consistency across pages. In addition, now if a user presses on the image in this page, it displays a larger version of the image (hence the new magnifying glass icon).

![newpage (2)](https://github.com/SeattleColleges/belindas-closet-android/assets/91910852/eacbbc58-e75e-4304-bf36-554af7f99955)

The larger image will dissapear if they press anywhere on the screen. Should we go with this new layout for the individual product page?
You can see the code for it in the new branch I just pushed.

**Comment by nickolasram** [comment]
@bcko @taylorpapke @brinkbrink @tinpham5614

**Comment by tinpham5614** [comment]
This looks nice! 😄
