### ISSUE TITLE
USER STORY: Password Reset Page

### ISSUE THREAD

**Issue by taylorpapke** [SeattleColleges/belindas-closet-android#159]
As an admin, I will want to have a way to receive an email to reset my password so that I can have a way to log in should I forget my password.

![password-reset-page](https://github.com/SeattleColleges/belindas-closet-android/assets/94101953/6f440e0f-8753-4dce-b623-e0c1659ff9c2)

Issues:
- [x] #218
- [ ] Password Reset Page: Forgot Password Page button sends email with link to reset password.
- [ ] Email link opens page in app to reset password with two inputs (new password/confirm password), and a button to reset password.
- [ ] Password reset page button confirms successful password change for the user’s email and routes to login page.

**Comment by brandondombrowsky** [comment]
Who is this assigned to and what project does it belong to?

**Comment by tinpham5614** [comment]
Password Reset Page: Forgot Password Page button sends email with link to reset password.
In my opinion, I think this task should be handled in the back end using **Nodemailer**. 
I will do research on this one.
