### ISSUE TITLE
USER STORY: Add Product Page Attach Image Button Functionality

### ISSUE THREAD

**Issue by taylorpapke** [SeattleColleges/belindas-closet-android#161]
As an admin, I will want to upload a picture of a clothing item from my phone to add to a product so I can have a picture representing the item I am uploading.

The following are examples from nsc-events-android. A button to attach a photo taken with phone to a product:
<img width="145" alt="Screenshot 2023-11-18 at 3 16 01 AM" src="https://github.com/SeattleColleges/belindas-closet-android/assets/94101953/35280385-fe43-48d4-ab85-2c1b3da4e834">
<img width="147" alt="Screenshot 2023-11-18 at 3 16 19 AM" src="https://github.com/SeattleColleges/belindas-closet-android/assets/94101953/e9ee0c77-664b-45cf-9a90-616f70614550">

- [x] #207
- [ ] Will need a way to convert the image to a String for storage
- [x] Should display thumbnail or say “attached” when successfully loaded
- [x] Toast message on button click

**Comment by brandondombrowsky** [comment]
Who is this assigned to and what project does it belong to?
