### ISSUE TITLE
USER STORY: Admin View Edit User Role Page

### ISSUE THREAD

**Issue by taylorpapke** [SeattleColleges/belindas-closet-android#162]
As an admin, I will want to be able to change a person's role so I can control what level of access others have.

![edit-user-role-page](https://github.com/SeattleColleges/belindas-closet-android/assets/94101953/c7103003-ba4d-4862-8de0-50c3637a7bf2)

- [ ] Edit user role button on admin view should redirect to an edit user role page.
- [ ] Edit user role page should list all user with change role button.
- [ ] Change role button should give option to change the user to one of the following roles:
- User
- Creator
- Admin 
- [ ] New changes should be reflected on User Role Page.

**Comment by Annelisebx** [comment]
Created[ Issue 167]:(https://github.com/SeattleColleges/belindas-closet-android/issues/167) EDIT USER ROLE: Add Page and List All Users/Roles, to address this USER STORY.
