### ISSUE TITLE
USER STORY: Edit Options Only Visible to Admin/Creator

### ISSUE THREAD

**Issue by taylorpapke** [SeattleColleges/belindas-closet-android#163]
As an admin, I will want to have edit option available to only myself and other creators so that users will not be able to have access to edit options and alter the products listed.

- [ ] Edit options should not be available when a user is not signed in.
- [ ] Edit options should not be accessible to the user role.
- [ ] Edit options should not persist after creator or admin signs out.
- [ ] Edit options only available to admins/creators that are signed in.

**Comment by brandondombrowsky** [comment]
Who is this assigned to and what project does it belong to?
