### ISSUE TITLE
USER STORY: Product Menu Dropdown Functionality

### ISSUE THREAD

**Issue by taylorpapke** [SeattleColleges/belindas-closet-android#164]
As a user, I will want to have a dropdown menu that will allow me to navigate to product category pages so I can always navigate to a different product page without having to back to the home page.

![product-menu-dropdown](https://github.com/SeattleColleges/belindas-closet-android/assets/94101953/32772fc8-61a4-4383-9180-c1c62ee8f6c7)

Issues:
- [x] [Product Menu Dropdown: Add Product Menu Dropdown](https://github.com/SeattleColleges/belindas-closet-android/issues/212)
- [x] Product (hamburger) menu should activate a dropdown on button click.
- [x] Dropdown should include the following product categories:
-Shoes
-Shirts
-Pants
-Skirt
-jacket/blazer
-Dress
-Casual wear
-Suits
-Accessories
- [x] Each dropdown menu item should redirect to its respective product category page.
- [x] #239

**Comment by brandondombrowsky** [comment]
Who is this assigned to and what project does it belong to?
