### ISSUE TITLE
USER STORY: Change Product Model

### ISSUE THREAD

**Issue by taylorpapke** [SeattleColleges/belindas-closet-android#168]
As an admin, I will want to have specific product categories so that all of my products can be placed in categories that represent them best.

Belinda only wants the following product categories:
- Shoes
- Shirts
- Pants
- Skirt
- jacket/blazer
- Dress
- Casual wear
- Suits
- Accessories

Issues:
- [x] SeattleColleges/belindas-closet-android#177
- SeattleColleges/belindas-closet-nestjs#62

**Comment by tinpham5614** [comment]
I've modified the ProductType on the front end to meet the client's requirements by removing unnecessary items.
I also created the issue SeattleColleges/belindas-closet-nestjs#62 for modifying the product model in the backend.
