### ISSUE TITLE
USER STORY: Finishing Tasks for Belindas

### ISSUE THREAD

**Issue by taylorpapke** [SeattleColleges/belindas-closet-android#169]
As an admin, I will want to have a few last changes implemented so the app looks the way I want it to look.

Issues:
- [x] Remove product name textbox from Add Product Page:
<img width="196" alt="Screenshot 2023-11-20 at 1 01 16 AM" src="https://github.com/SeattleColleges/belindas-closet-android/assets/94101953/0a29b192-4618-4134-9a1c-45cd47974515">

- [x] Change “resupply” to “sign up” on Sign Up Page:
<img width="195" alt="Screenshot 2023-11-20 at 1 04 43 AM" src="https://github.com/SeattleColleges/belindas-closet-android/assets/94101953/ccff340f-b11d-4dba-9466-b15db6537db6">

- [x] Change frog color to green on Sign In Page:
<img width="203" alt="Screenshot 2023-11-20 at 1 06 18 AM" src="https://github.com/SeattleColleges/belindas-closet-android/assets/94101953/c489df18-57d7-4a20-8780-6447a7e83961">

**Comment by brandondombrowsky** [comment]
Who should this be assigned to and what project is it associated with?
