### ISSUE TITLE
USER STORY: Product Entity Consistency Between Front/back End

### ISSUE THREAD

**Issue by CourtneyHoppus** [SeattleColleges/belindas-closet-android#172]
Relates to Back-End [Issue 59](https://github.com/SeattleColleges/belindas-closet-nestjs/issues/59)
As a developer, I will want the Product entity to be consistent across the front-end and the back-end.

Currently the shape of the data that represents a Product is not the same.

The [front-end schema](https://github.com/SeattleColleges/belindas-closet-android/blob/main/app/src/main/java/com/example/belindas_closet/model/Product.kt) has the following properties with data types:

- ProductType: enum [SHOES, LONG_SLEEVE_SHIRT, SHORT_SLEEVE_SHIRT, PANT, SKIRT, TIE, BELT, JACKETS, DRESS, HAT, SOCKS, HANDBAG, SCARF, GOWN, HOODIE, SWEATER, VEST, OTHER]
- ProductGender: enum [MALE, FEMALE, NON_BINARY]
- ProductSizeShoes: enum [SELECT_SIZE(null), XS(5), S(6), M(7), L(8), XL(9), XXL(10), XXXL(11), XXXXL(12)]
- ProductSizes: enum [SELECT_SIZE, XXS, XS, S, M, L, XL, XXL, XXXL, XXXXL]
- ProductSizePantsWaist: enum [SELECT_SIZE(null), XS(28), S(30), M(32), L(34), XL(36), XXL(38), XXXL(40), XXXXL(42)]
- ProductSizePantsInseam: enum [SELECT_SIZE(null), XS(28), S(30), M(32), L(34), XL(36), XXL(38), XXXL(40), XXXXL(42)]
-  val productType: ProductType
    val productGender: ProductGender
    val productSizeShoe: ProductSizeShoes
    val productSizes: ProductSizes
    val productSizePantsWaist: ProductSizePantsWaist
    val productSizePantsInseam: ProductSizePantsInseam
    val productDescription: String
    val productImage: String = R.drawable.placeholder.toString()
    val id: String = "0"

The [back-end schema](https://github.com/SeattleColleges/belindas-closet-nestjs/blob/main/src/products/schemas/product.schema.ts) has the following properties with data types:
 - createByUserID: string
 - productType: []
 - gender: []
 - productShoeSize: []
 - productSize: []
 - productSizePantsWaist: []
 - productSizePantsInseam: []
 - productDescriptionOptional: string
 - productImage: string
 - isHidden: boolean
 - isSold: boolean
 
The entity properties need to match. This entails refactoring both entities to have the same data shape. This will also require refactoring any files that uses the Product entities in both repos.

---------

Front-end Update:
- need to include the following properties: createByUserID, isHidden, and isSold

Back-end Update:
- change productShoeSize to productSizeShoe, productSize to productSizes, gender to productGender, productDescriptionOptional to productDescription

Questions about the properties:
- I think that ProductSizes should be an array of ProductSizes. Also I think we need numerical values as well as letter sizing. An item could be a size 10, and could be considered both a medium (M) and a large (L). Same as a product could be labeled medium, and it fits a 8/10. Clothing sizing isn't very consistent. We would want any search or category functionality to have more listings than a person would fit, not less.
- I think that ProductType should be an array of ProductTypes. An item could be a sweater and a vest (a sweater vest) or an item could be a sweater and a short-sleeve-shirt. I know people use sweater and sweatshirt interchangeably, so one could argue a hoodie is also a sweater or a long-sleeve-shirt or both. I also think the enum list needs to be expanded to include TOPS, BOTTOMS, BUTTON_UP_SHIRT, BLOUSE, and ACCESSORIES. I would also suggest replacing HOODIE with SWEATSHIRT.
- I think that ProductGender should replace NON_BINARY with UNI_SEX or GENDER_NEUTRAL, I think non-binary is more of a personal adjective/identity than a descriptor for clothing. Maybe also an array?
- For productSizePantsWaist and productSizePantsInseam, why are the enums a number value represented by a letter size? The letter sizing is taken care of in the ProductSizes. I think these should just be numeric values.
- For productSizeShoe I also think this should be just numerical, I have never seen shoes listed as S, M, etc.

----------
@bcko @brandondombrowsky @brinkbrink @taylorpapke @Robel-003 @tinpham5614 @theGaryLarson @Seiyaroo 
Any discussion/input would be great before moving forward.
I understand some of the questions I brought up might be a PO/client conversation, happy to refactor however it has been decided.

**Comment by brandondombrowsky** [comment]
I have strong positive feelings for your comments. I think your assessments/assertions are pretty spot on. This is something Taylor and I have working on since very early on. I am curious to know what @taylorpapke thinks as the PO. 

As an aside, thank you for following tagging conventions!

**Comment by taylorpapke** [comment]
Hey @CourtneyHoppus, I had already created a user story for this https://github.com/SeattleColleges/belindas-closet-android/issues/168. Please rename both of this issue using the proper formatting pointing back to that user story as to avoid confusion. 
This should be renamed as follows:
Change Product Model: Product entities need to be consistant across front and back ends

Refactor is a branch naming convention @tinpham5614

**Comment by brinkbrink** [comment]
I don't have much to add but also love this. Thank you!

**Comment by taylorpapke** [comment]
@CourtneyHoppus I do not have strong requirements from the client for the properties. However, I do have strong requirements for the product types themselves. Please see USER STORY https://github.com/SeattleColleges/belindas-closet-android/issues/168 as it answers some of your questions in regard to these products.

I do have an opinion in regard to everything else. I propose that we keep the properties and size ranges as average and simple as possible. We must remember that all fields are optional aside from the productType (and potentially image - I can't remember what we decided on this). Anything else can be typed into the optional description field.
I propose the following:
ProductType: enum [Shoes, Shirts, Pants, Skirt, jacket/blazer, Dress, Casual wear, Suits, Accessories]
ProductGender: enum [MALE, FEMALE, UNI_SEX]
ProductSizeShoes: enum [SELECT_SIZE(null), 4, 4.5, 5, 5.5, 6, 6.5, 7, 7.5, 8, 8.5, 9, 9.5, 10, 10.5, 11, 11.5, 12, 12.5, 13, 13.5, 14, 14.5, 15, 15.5, 16, 16.5, 17]
ProductSizes: enum [SELECT_SIZE, 0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, XXS, XS, S, M, L, XL, XXL, XXXL, XXXXL]
ProductSizePantsWaist: enum [SELECT_SIZE(null), (28), (30), (32), (34), (36), (38), (40), (42)]
ProductSizePantsInseam: enum [SELECT_SIZE(null), (28), (30), (32), (34), (36), (38), (40), (42)]

**Comment by tinpham5614** [comment]
Is this user story currently being worked on?

**Comment by CourtneyHoppus** [comment]
> Is this user story currently being worked on?

Yes @tinpham5614 I am about to create a PR.
