### ISSUE TITLE
App Improvements

### ISSUE THREAD

**Issue by brandondombrowsky** [SeattleColleges/belindas-closet-android#50]
We will use this as a collection of potential app improvements that anyone can undertake in their free-time and research. Feel free to write them down here and edit your post as you find / think of them.

**Comment by tinpham5614** [comment]
Hi team,
As a software developer, I would like to make every page in an app consistent. I noticed that there is a difference when we created a Top App Bar for the Login, Add Product, and Sign Up pages we haven't used Scaffold yet. I would like to create an issue to modify this. What do you guys think?
Here are examples:
Without **Scaffold**
![Screen Shot 2023-10-15 at 3 38 07 PM](https://github.com/SeattleColleges/belindas-closet-android/assets/72054441/5ade881c-0c9f-4b43-9451-86b4ffcafc72)
With **Scaffold**
![Screen Shot 2023-10-15 at 3 39 02 PM](https://github.com/SeattleColleges/belindas-closet-android/assets/72054441/63c18244-9a70-4139-b418-aa1c02d711e3)
