### ISSUE TITLE
BE - Route Stubs

### ISSUE THREAD

**Issue by brandondombrowsky** [SeattleColleges/belindas-closet-android#51]
As a developer, I will want to make sure the routes our client/customers will be going to are available to them.

**Describe the solution you'd like**
In the proper location(s) within the code, I will stub out the routes in a basic fashion so that our front-end developers can access them as they navigate our application during their design process.

Use the following diagram as a guide:

![Image](https://github.com/SeattleColleges/belindas-closet-android/assets/80282265/0a7f679a-d300-4250-a25d-a384851e7961)

**Comment by brinkbrink** [comment]
@taylorpapke can you please convert [this](https://user-images.githubusercontent.com/64063020/271445479-b19b7f9f-af4a-432e-b3bd-28894d983456.png) or go through it with Tin to modify it for Belinda's so it can be used for this issue?

**Comment by brinkbrink** [comment]
I'm going to put Robel on this now that I know they he has availability to help us out with back-end dev work.
