### ISSUE TITLE
USER STORY: Navigation Bar

### ISSUE THREAD

**Issue by taylorpapke** [SeattleColleges/belindas-closet-android#74]
As a student, I will want to have a simple way to navigate the app to find clothes so that I can spend less time searching for what I am specifically looking for.

- Products menu added to navigation.
~- Product categories added as submenus for products menu (jeans, coats, etc.).~
~- Products menu will redirect to home page where all categories are shown.~

![Image](https://github.com/SeattleColleges/belindas-closet-android/assets/94101953/ca0aabb8-31e3-4fec-8e1a-1061454db3ee)

Documentation

https://developer.android.com/jetpack/compose/components/scaffold
https://developer.android.com/jetpack/compose/components/app-bars

Tutorials

https://www.youtube.com/watch?v=EqCvUETekjk

**Comment by Annelisebx** [comment]
The Home Screen and Product Details page are already created, correct? I will be creating an extra layer that further organizes all products by category.

**Comment by taylorpapke** [comment]
Sorry @Annelisebx for not responding to this earlier. This user story is strictly in regards to creating a navigation bar with a products menu link. The link should be a dropdown with the category submenus which should link out to the products screen where all the clothing items for that category can be found. 
It would also be nice if clicking products itself would return directly to the home page while maybe a down arrow next to it could be the dropdown with submenu items. We should probably refer to material 3 to find a better standard for this as I am not so sure. do you have any thoughts on how this should be implemented?

**Comment by Annelisebx** [comment]
@taylorpapke Should this navigation bar be accessible on all 3 screens? (Home, Products, and Product Details)

**Comment by taylorpapke** [comment]
@Annelisebx I think a good reference for this user story is https://github.com/SeattleColleges/nsc-events-android/issues/58 and what @kkennedy-gh did in here in PR https://github.com/SeattleColleges/nsc-events-android/pull/85/files. We can probably just do something like this and make the small changes to fit our requirements for Belindas.

**Comment by taylorpapke** [comment]
@Annelisebx I’m reducing the scope of this user story a little bit as there is a lot to this one. Let’s just do the creation of the navigation bar for each page with the product menu icon and back buttons where needed. We can make another user story to deal with adding product category links to the menu icon (lets only worry about making the back buttons functional for now). This will allow me to get more feedback from the client on what exactly they want before we proceed any further. I’ve edited the user story above.

**Comment by taylorpapke** [comment]
Hi @Annelisebx, which screens still haven't been started? Let's give @MuhammadNSC and @kaimanasse15 each a screen to work on.

**Comment by MuhammadNSC** [comment]
Hi all! I'm going through the workflow of this Issue to get an idea of what has been done so far. Let me know that screen that still needs work done

**Comment by taylorpapke** [comment]
@Annelisebx @kaimanasse15 @MuhammadNSC I went ahead and updated the diagram above to better show what this user story should be accomplishing for all of the pages in the app.

**Comment by Annelisebx** [comment]
Create [Issue 194 ](https://github.com/SeattleColleges/belindas-closet-android/issues/194)for adding navigation elements to 'update' pages
