### ISSUE TITLE
USER STORY: Products Page

### ISSUE THREAD

**Issue by taylorpapke** [SeattleColleges/belindas-closet-android#75]
**Make sure the first line is formatted as follows.**\
As a student, I will want to have a products page that shows all the products from a specific category so that I can see what is available for that category.

- Leverage existing product details page to create a page that shows all products from a product category.
When a product is clicked, user will be taken to the product detail page.
- Styled per general guidelines but pending client approval.
- Has appropriate features given what it will be used for (reach out to PO for amplification).

Resources:
- https://m3.material.io/
- https://developer.android.com/jetpack/compose/designsystems/material3

![Image](https://github.com/SeattleColleges/belindas-closet-android/assets/94101953/b3ff8c94-e315-4038-a1fa-730edcd058a2)

**Comment by brinkbrink** [comment]
You can create stand-in themes with [Material 3 theming](https://developer.android.com/codelabs/jetpack-compose-theming#0) that will be edited later (so don't spend too much time on this). No colors, styles, or design beyond this mock-up have been confirmed by the client.

**Comment by brinkbrink** [comment]
Let's get a unified approach to the product schema w/r/t how the categories are listed.

**Comment by tinpham5614** [comment]
According to the diagram above,
**My understanding is:**
Home Page will contain productType. For example: Shoes, Pants, etc.
Products Screen (currently Product Details) will contain products. For example Shoes1, shoes2, shoes3, etc. (if users click shoe category)
Product Details will contain individual product details. For example name: shoes, size: 7, gender: male, etc.
**My opinion:**
We need to refactor codes on the Product Details page (which will be the Product Page) to show products belonging to that category.

**Comment by nickolasram** [comment]
I have a version of the Product Details page that is able to do that. Once we finish updating the product model I can finalize that and publish it. My suggested updates to the product model are on issue #92 .

> According to the diagram above, **My understanding is:** Home Page will contain productType (category). For example: Shoes, Pants, etc. Products Screen (currently Product Details) will contain products. For example Shoes1, shoes2, shoes3, etc. (if users click shoe category) Product Details will contain individual product details. For example name: shoes, size: 7, gender: male, etc. **My opinion:** We need to refactor codes on the Product Details page (which will be the Product Page) to show products belonging to that category.
