### ISSUE TITLE
Attach image string to category ENUM

### ISSUE THREAD

**Issue by nickolasram** [SeattleColleges/belindas-closet-android#92]
The current product model in Pull Request #85  looks like:
 
`
enum class ProductType(val type: String) { 
    SHOES("Shoes"), 
    LONG_SLEEVE_SHIRT("Long Sleeve Shirt")
}
`

I suggest changing it to something like:
`
enum class productType(val type: String, val image: String){
    SHOES("Shoes", R.drawable.type1.toString()),
    LONG_SLEEVE_SHIRT("Long Sleeve Shirt", R.drawable.type2.toString())
}
`

This will allow us to couple the product type with the image that's supposed to go along with it.

Additional Note:
You should be able to get a list of productTypes by using productType.values().

**Comment by nickolasram** [comment]
@tinpham5614 @theGaryLarson @brinkbrink @taylorpapke @bcko

**Comment by taylorpapke** [comment]
@nickolasram So this would be a way to tie a non-unique productType with a unique image in order to make the resulting product unique while allowing it to sit under its (productType) category? I think I like it. Would this mean that an image will be required for every product (which would be fine of course)?

**Comment by tinpham5614** [comment]
I like the idea that each category will now have an image to present.

**Comment by nickolasram** [comment]
> @nickolasram So this would be a way to tie a non-unique productType with a unique image in order to make the resulting product unique while allowing it to sit under its (productType) category? I think I like it. Would this mean that an image will be required for every product? (which would be fine of course)

Yeah, each productType would have a picture and each individual product would have its own image (though we could have a "default" placeholder image to slot in if, say, we didn't have a picture for a given product yet)
