### ISSUE TITLE
Create Navigation Bar

### ISSUE THREAD

**Issue by Annelisebx** [SeattleColleges/belindas-closet-android#97]
**Make sure the first line is formatted as follows.**\
As a developer, I will want to create a navigation bar that allows the user to select products by category.

**Include link(s) to relevant tutorial(s)**\
Please include at least one link to a relevant tutorial for the issue to give developers a starting point. 

**Describe alternatives you've considered**\
Navigation Drawer: 
![image](https://github.com/SeattleColleges/belindas-closet-android/assets/50610153/66849fd8-c95b-48c8-83ef-721320e6a1a5)

Toolbar with Tabs on top: 
![image](https://github.com/SeattleColleges/belindas-closet-android/assets/50610153/fe592087-51d4-4d78-a58a-c74b7f40abe3)

A drop down menu of categories when on the products page to search by categories you are not currently viewing. 

**Is this issue related to any other issues?**\
Issue for [User Story 74: Navigation](https://github.com/SeattleColleges/belindas-closet-android/issues/74)

**Additional context**\

**Story Points**\
Please estimate amount of story points. Each story point is defined as 30 minutes.

**Comment by Annelisebx** [comment]
Closed with [PR 114](https://github.com/SeattleColleges/belindas-closet-android/pull/114)

**Comment by brinkbrink** [comment]
@Annelisebx I reverted the branch within minutes of you saying that you did not want it merged. Please let me know what you want.
